### ISSUE TITLE
Mode: Ask if no rule applies

### ISSUE THREAD

**Issue by mahoromax** [aloneguid/bt#40]
Hi, I believe this is easy to adapt and it really would fit the "learning" behaviour of it.

-> URL that doesn't fit any rule? -> Ask and add rule
-> URL that should always be asked -> Ask and do not add a rule

**Comment by aloneguid** [comment]
I assume you have tried this and it doesn't work for you? 
<img width="362" alt="image" src="https://github.com/aloneguid/bt/assets/3155189/022b1807-a4ef-4d25-9967-e706dbeea17b">

I like the idea of adding rules that must always trigger the picker!

**Comment by adynis** [comment]
I also would like to have an option that shows the "Picker" by default (when no rule apply) , and the selecgted browser when one rule matches.
It's not very clear to me what "Conflict" means on "Ask on Conflict" , but I would see very usefull an additional option there like: "Ask when no rule"

**Comment by aloneguid** [comment]
I appreciate your feedback, it's very helpful. I agree that "ask on conflict" is not a clear or common option - it only pops up a dialog when there are multiple browsers/profiles that can open a certain URL. I think you're right that I should add another option like you suggested - "Ask when no rule matched". That would make it easier for users to choose the browser/profile they want when there is no rule defined. How does that sound?

**Comment by Mythrix** [comment]
I would also like an option like "Ask when no rule matched" in any case.

I used to use [BrowserSelect](https://github.com/zumoshi/BrowserSelect) which worked like that: Pop up the option to select a browser for all URLs, but if a rule is found, it will autopick the browser. (I switched away from that tool because it tended to add duplicate copies of each browser in the list when refreshing browsers, which got annoying after it happened a few times.)

Although now I decided to try using the "Also open on" feature in combination with "Ask on conflict" in BrowserTamer. Which does kinda solve my use case, as long as I remember to hold down the keyboard shortcut when clicking on links.

**Comment by Mythrix** [comment]
PS: I almost never remembered to hold down the shortcut keys when clicking on links. Additionally, holding down the keys would mess with some apps (specifically Outlook tends to act weirdly when I hold down certain keys and try to click.) So that did not really work out at all...

In the end I tried out other alternatives, but many did not support browser profiles well. Eventually I got to [Switchbar](https://switchbar.com/) which supports both "Ask if no rule applies" and browsers with multiple profiles. So other people with the same issue could consider trying that option. Do note that Switchbar has a free and a paid version, and the free version only supports 2 "favorite" browsers/profiles (but for me that was enough, for now at least.)

In any case, it would be great if BT could also get the option to show the picker only when no rules are matching.

**Comment by aloneguid** [comment]
This will be coming in v4, something like this:

<img src="https://github.com/aloneguid/bt/assets/3155189/4ebb511f-fa2d-4731-872c-c33bc0e40252" height="200"/>

**Comment by aloneguid** [comment]
done

**Comment by Mythrix** [comment]
Hi, thanks for your hard work!

Unfortunately I was unable to get the "On no rule" option to work properly. In fact, it is possible that even the "On conflict" option does not work anymore in v4.

I have tried:

- Using only the "On no rule" option
  - This just opens in the default browser (unless there's a rule in effect)
- Using just the "On conflict" option
  - Same as above, additionally even if there is a conflict, it just opens up in the first(?) browser that has the rule
- Using both the "On no rule" and "On conflict" options
  - Same as above
- Deleting (renaming) config.ini to get a completely "fresh" BT configuration
  - Did not seem to help
- Uninstalling v4 and reinstalling v4 again
  - Did not seem to help
- Also rolled back to v3.7.3 to doublecheck
  - "On conflict" seems to wwork properly there

This is on a Windows 10 22H2 PC.

Do not worry about prioritizing this bug in any case, I can understand that it's hard to take time for an opensource hobby project. And I hope it's not just me doing something wrong in my settings/usage...

**Comment by aloneguid** [comment]
Yes you're right, that slipped in. Hope to fix this today!

**Comment by Mythrix** [comment]
Thanks for the quick fix!
I tested a little bit now, and both "On no rule" and "On conflict" seems to work properly now.
And the integration with Firefox containers also seem to work great when using the rules!
👍
