### ISSUE TITLE
Pick a Browser window freezes with cromium based browsers with versions > 3.5.1

### ISSUE THREAD

**Issue by cjs1976** [aloneguid/bt#51]
Hello,

I've tried it with three different systems. With the version 3.5.1 everything works well, but with the later versions (I've tried up until the 3.6.1) the Pick-a-Browser window freezes upon choosing between Chrome, Brave, Opera, Epic, Maxthon, etc... The browser window opens with the right url, but the Pick-a-Browser window is still there and has no reaction. What's even stranger is that with Firefox, Firefox Developer Edition and Edge it is still working. Also, if I close the browser window, the Pick-a-browser window closes too and everything runs normal. If I click many times the "Pick-a-Browser" window, or if I try closing it, the app crashes.

Am I doing something wrong here?

Many thanks,
Christian

**Comment by fixator10** [comment]
It doesnt related to chromium, since for me it happens also with Links browser and MPV. It seems to be that a BrowserTamer waits for process its spawned to end. 

If browser is already open at the moment of choosing its works just fine, but if browser is closed, the process spawned by BT becomes main process of the browser and doesnt die immediately

**Comment by aloneguid** [comment]
Yes you're right, broken in #39 since 3.5.2. BT will wait for proxy process to exit which is not always the case.

**Comment by aloneguid** [comment]
should be fixed in 3.6.2
